### ISSUE TITLE
Support `pino@8` in `@opentelemetry/instrumentation-pino`

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#1071]
`@opentelemetry/instrumentation-pino` doesn't have a component owner, but was contributed by @seemk.
Could you, by any chance, take a look?

**Comment by zemd** [comment]
while I was trying to fix the https://github.com/open-telemetry/opentelemetry-js-contrib/issues/854 and also figuring out how to adopt pino@8 with opentelemetry I ended up with the thought that there is no need to make and maintain instrumentations for js loggers at all. Because each user always creates his own logger instance and shares it within the app, and each user configures this instance for each project, so no need to intercept module loader, that can break things and can be unstable due to issues like https://github.com/open-telemetry/opentelemetry-js-contrib/issues/854

So I think it so much easier to add manually `mixin` for the pino configuration:
```
export const logger = pino({
  // ... 
  mixin: () => {
    const record = {}
    const span = trace.getSpan(context.active());
    if (span) {
      const spanContext = span.spanContext();

      if (isSpanContextValid(spanContext)) {
        Object.assign(record, {
          trace_id: spanContext.traceId,
          span_id: spanContext.spanId,
          trace_flags: `0${spanContext.traceFlags.toString(16)}`,
        });
      }
    }
   const appCustomField = { bar: 'baz' };
   return Object.assign(appCustomField, record)
  }
})
```

and that's it. As improvement strategy `opentelemetry` lib can provide such type of helper function which would build desired object, instead of patching module.

**Comment by dyladan** [comment]
I think we need to start enforcing ownership more forcefully the way the collector does. One way to start would be to add a section to each README of a component without an owner stating that it does not have a maintainer and should be treated as beta

**Comment by Flarna** [comment]
The idea of autoinstrumention like `@opentelemetry/instrumentation-pino` is to have no manual tasks. Add OTel + wanted instrumentations to whatever app and it is traced/log enriched/...
All autoinstrumentations could be replaced by creating spans manually and it would be most likely less risk for the app, less overhead. But each and every dev has to do this in their app/lib.

**Comment by zemd** [comment]
> is to have no manual tasks

This is valid intent! But taking pino-instrumentation as example we can see that the plugin is just replacing some amount manual tasks from one place to another, in the same time hiding issues. 

For example, package upgrade from pino@7 to pino@8 can be forced by any modern automation tool/bot. And when developer looks inside `package.json`- he won't see any issues until he start observing traces/metrics.

Also to guarantee that otel works correctly otel lib should somehow inform developer that he should use imports correctly(in terms of instrumentation like we saw in https://github.com/open-telemetry/opentelemetry-js-contrib/issues/854).

Additionally patching library doesn't guarantee that it would work, since there are node's issues, like described in this doc https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-context-async-hooks (I'm talking here specifically about limitation section and provided link https://github.com/nodejs/diagnostics/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aasync-continuity).

So my comment where I manually added spans just shows that overhead provided by at least `pino` instrumentation doesn't necessary be solved from the current point of view, as instrumentation. But on the contrary it should strictly guide the developer what should be done to achieve specific outcome. That means that it easier, and more reliable to provide function like `(): MandatoryTraceFields => {  // using spans and returning { trace_id: '...' }  }` that I can use for my almost **any** logger(which to say I definitely would know better than instrumentation logic) instead adding `pino-instrumentation` as dependency and trying to find out what exactly doesn't work.

Couple words about `auto-instrumentation`. Despite of this package is intending to be analog of babel/preset-env, but so far it reduces guarantees for the project, since it hides issues https://github.com/open-telemetry/opentelemetry-js-contrib/issues/854. And I'm not sure that projects need to log everything that can be matched with this package. I'm a proponent of limiting dependencies and adding only what the project really uses. But this is only my own opinion.

**Comment by seemk** [comment]
This package was mostly meant for auto instrumentation implementations. How would you achieve trace and log correlation when using auto-instrumentation SDKs?

This package thus far has been supporting up to Pino 8. If no warnings for newer versions appear, then perhaps we'd need to change [instrumentation code](https://github.com/open-telemetry/opentelemetry-js/blob/b8915092bc15e0b38b0388463e05308a438282ac/experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts#L110) to log a warning? Not arguing an update is not necessary for a new major version, but I'm trying to understand the other complaints here 🙂

**Comment by Rauno56** [comment]
So this issue here was solely to track the missing support of pino@8 from the package. The question whether @seemk is able or willing to take that still stands.

What comes to https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1071#issuecomment-1172617330, I created [another issue](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1080) for that.

In regards to @zemd comments I think that's a whole another topic on it's own - I think your points are worth discussing and kindly invite you to open a separate issue for doing that, since it's a broader question than the support for auto instrumentating a specific pino version.
