### ISSUE TITLE
Incentivising package ownership

### ISSUE THREAD

**Issue by rauno56** [open-telemetry/opentelemetry-js-contrib#1080]
@dyladan [wrote](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1071#issuecomment-1172617330):

> I think we need to start enforcing ownership more forcefully the way the collector does. One way to start would be to add a section to each README of a component without an owner stating that it does not have a maintainer and should be treated as beta

Documentation about that [here](https://github.com/open-telemetry/opentelemetry-collector#stability-levels).

I think it's a great idea. Even though we're very grateful for any contribution of a new package, I don't see how the maintainers of Otel JS could ever reliably guarantee the continued maintenance, upgrades and support for all the packages ever contributed.

How it **could** look like in contrib:

1. All pacakges are given a stability level:
   - Packages with a component owner will most likely be in `Beta`
   - Packages without a component owner will be `Unmaintained` and we'd be open for anyone picking up the responsibility for maintaining those
2. The stability level will be documented in the readme and `package.json` file
3. General repo-wide versioning and workflow updates will still be contributed by the maintainers
4. We'll follow the lead of https://github.com/open-telemetry/opentelemetry-js/pull/3058 and help reporters to label all issues according to the package they are about + assign the component owners to triage and potentially(still open for any contributions) work on those issues. The attendance of those issues will be the basis of relabeling the stability level for any package.
5. After 6 months, if a package has not found a maintainer we'll be replacing the package with a readme file noting it's past existence and steps to bring it back for anyone interested.

**Comment by Flarna** [comment]
> 5\. After 6 months, if a package has not found a maintainer we'll be replacing the package with a readme file noting it's past existence and steps to bring it back for anyone interested.

I think there is no reason to remove on default after 6 month. It's likely that things keep working significant longer then 6 month if the instrumented module is not release frequently / only with minor changes (e.g. winston, express, connect).

**Comment by dyladan** [comment]
@Flarna I think he's saying after 6 months with an unsolved issue and no maintainer, not just 6 months without any updates. Maybe we can use the bug priority levels documented [here](https://github.com/open-telemetry/opentelemetry-js/blob/main/maintenance/bug_triage.md#prioritize) to have a more nuanced policy. There are also steps less severe than removal we can use (note in readme, deprecate in NPM, remove from auto instrumentation package, etc).

**Comment by Rauno56** [comment]
My goal wasn't to make the code disappear, but to

1. Lift the burden of maintaining it from the maintainers - tooling and SDK compatibility upgrades etc;
2. Communicate the fact that that is unmaintained and might have issues.

It's easy to assume that whatever is in the contrib repo is of high quality and we do our best for sure, but in the absolute worst case scenario people could theoretically dump really raw packages here leaving an impression that everything will be polished over time and then just disappear - that's essentially the situation I'd like to avoid.

Since we're working with git, rolling changes(like removing a package) back is trivial. Having the last state of the code still checked in is also valuable for people who want to troubleshoot something or would be interested in bringing the package up to date, on the other hand.

**Comment by jscherer92** [comment]
I just want to throw my hat in the ring to be the maintainer of the graphql package. I have a very intimate knowledge of GraphQL and this is one that I am continuing to try to improve for my own use cases and others. @dyladan @Flarna @Rauno56 let me know if this is good for all of you.

**Comment by Flarna** [comment]
@jscherer92 Sounds good
