### ISSUE TITLE
Options to set only span key in span name of memcached instrumentation

### ISSUE THREAD

**Issue by aadharsh-rengarajan** [open-telemetry/opentelemetry-js-contrib#1102]
In memcached instrumentation, we get span name like

```
 set api:1:value
 get api:1:value
```

which creates a difficulty when we want to group the span names and observe it for metrics purposes.

In our case, we would need to add an option that would let us only get memcached key instead of key:value like this
```

get or memcached:get
set or memcached:set

```
instead of
```

get api:1:value
set api:1:value

```
### Describe the solution you'd like to see

The solution would be adding an option along with enhancedDatabaseReporting. That would let us decide if we need the entire span with key value pair or just the key.

I would need an additional option where we can just ignore the memcached key in the span name and instead have query.type alone as the span name instead of query.type and query.key as mentioned below.

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2229cbe3b503e2b7c54f657e9f29698cc9f8f380/plugins/node/opentelemetry-instrumentation-memcached/src/instrumentation.ts#L37

Here we can add an additional option where we set a key called `cleanSpanName` which defaults to false. We can refer the cleanSpanName below in the place below. 

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2229cbe3b503e2b7c54f657e9f29698cc9f8f380/plugins/node/opentelemetry-instrumentation-memcached/src/instrumentation.ts#L141

Where we just check this condition: ` const result = ( cleanSpanName ) ? span.updateName(`${query.type}`): span.updateName(`${query.type}  ${query.key}`);
### Describe alternatives you've considered

We can ignore the memcached value (query.key) in the span name as it is redundant and can be taken from span attributes..

**Comment by RahulGanesh08** [comment]
+1 to this , since the telemetry instrumentation uses operation it performs  `get ,set`  and  memcache key` api:1:value` for the span name .  which results in much noise as jager considers every memcache operations unique since the key is present rather than grouping them by the opertions. 

as the solution mentioned above just like an option for `enhanced database reporting` , an option for filtering out the key from the span name would be very useful for many usecases.

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-memcached/src/instrumentation.ts#L141

**Comment by dyladan** [comment]
I would actually argue we should just remove the value from the name entirely. The specification wants low cardinality span names and the value can be extremely high cardinality. This is actually the reason for the spec being the way it is.

**Comment by aadharsh-rengarajan** [comment]
Indeed it is of very high cardinality. Going forward with removing the value from the span name.
