### ISSUE TITLE
Pin/restrict typescript version for all components

### ISSUE THREAD

**Issue by osherv** [open-telemetry/opentelemetry-js-contrib#1145]
Today, every sub-package in the repo specifies its own typescript version.
There is no restriction and every package can use a different version of typescript which can cause many collisions and errors like: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1141

I wonder how can we avoid those collisions in the future.
We want that all of our packages will use the same version (currently `4.3.5`).

**Comment by blumamir** [comment]
Actually, typescript is already a dependency of the monorepo root [here](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/ec9ee131635dc2db88deea4f2efb887ff6f60577/package.json#L59), so I guess it's reasonable that sub packages should be able to pick it up from there instead of specifying the dependency again and again.

I guess the package manager can sometimes be confused when executing various scripts that invoke `tsc`, but that is easy to test if you are up for it 😉

**Comment by osherv** [comment]
Be sure i am :)
