### ISSUE TITLE
Add plugin for restify

### ISSUE THREAD

**Issue by kintel** [open-telemetry/opentelemetry-js-contrib#134]
This is supported by the current offerings of at least Google (https://github.com/googleapis/cloud-trace-nodejs#what-gets-traced) and Lightstep (https://docs.lightstep.com/docs/nodejs-auto-instrumentation#frameworks), so it would be good to have it added in OpenTelemetry.

**Comment by menishmueli** [comment]
Hi, I want to start contributing to OpenTelemetry, can I grab this issue?

**Comment by kintel** [comment]
@adamegyed You mentioned this yesterday. Could you update your plans here and/or sync with @menishmueli ?

**Comment by adamegyed** [comment]
Hi @menishmueli ! I've started work on this plugin a while back, but ran into some blockers and held off on claiming the ticket. Recently though I think I found a solution, and I plan on starting a draft PR today. Feel free to contribute to it if you'd like.

**Comment by Rauno56** [comment]
Hi, @adamegyed! How far did you get with the implementation?
I'd love to start working on it and either take your work to the finish line or start my own.

**Comment by adamegyed** [comment]
Hi @Rauno56! I ended up pivoting to a different project at the time, but if you want an idea of how instrumenting a new plugin is done, you could take a look at how the Hapi integration was implemented here: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/171. I do believe that some of the organization around plugins and instrumentation might have changed since, so it might also help to look at more recent PRs and the spec.

**Comment by Rauno56** [comment]
Thanks, @adamegyed!
Restify instrumentation landed in b7d84d1 #416, but not yet published.

**Comment by Rauno56** [comment]
Can be closed now, @vmarchaud.
