### ISSUE TITLE
Should dependabot be enabled ?

### ISSUE THREAD

**Issue by abhee11** [open-telemetry/opentelemetry-js-contrib#1448]
- [x] This only affects the JavaScript OpenTelemetry library
- [ ] This may affect other libraries, but I would like to get opinions here first

Within Appdynamics we had a security discussion and realized that dependabot was disabled sometime in 2020 for js-contrib. However dependabot is enabled for other repositories within otel space. It seems like dependabot could play a role in identifying and fixing security vulnerabilities. 

I am sure there was a reason to disable it, just trying to understand what those are, can we be looking at enabling it anytime soon ? if not ? why not ?

**Comment by Flarna** [comment]
The js repos use renovate but it seems it's not working here since a while. see https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1434

it seems also that a lot PRs created by renovate are not that helpful as it tries to update to many dependencies at once resulting in build failure and therefore automation is actually gone.
