### ISSUE TITLE
onclick - react, zone.js

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-js-contrib#168]
Investigate problem with onclick event for react when using plugin for user interaction , react plugin, xmlhttprequest plugin, and zone manager.
More context here -> https://github.com/open-telemetry/opentelemetry-js-contrib/pull/164#issuecomment-668811140

**Comment by kkruk-sumo** [comment]
I also found this bug recently. It looks like React attaches event listener only to root elements (or `document` for versions < 17.0.0).
`instrumentation-user-interaction` doesn't work here, because of this condition (`document` doesn't have the `getAttribute` method):
```ts
if (!element.getAttribute) {
  return undefined;
}
```

Changing the logic works, but the `xpath` is mapping to `/` (document).

The original event is still accessible though as the first extra argument.
