### ISSUE TITLE
[opentelemetry/auto-instrumentations-web] esm directory missing in release 0.34.0

### ISSUE THREAD

**Issue by adamlyka** [open-telemetry/opentelemetry-js-contrib#1799]
When attempting to use the latest version of opentelemetry/auto-instrumentations-web my project fails to build with the following error: 
`Failed to resolve entry for package "@opentelemetry/auto-instrumentations-web". The package may have incorrect main/module/exports specified in its package.json.`

I noticed the esm directory was missing and causing the failure:
https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-web/src

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/99db4bb89d717b65c6f91461e466882b09677852/metapackages/auto-instrumentations-web/package.json#L15

**Comment by JamieDanielson** [comment]
I was looking into this and was able to repro using [Vite](https://vitejs.dev/), which [sets ESNext as the transform target](https://vitejs.dev/guide/#browser-support). I used one of the web example apps with Vite instead of webpack (`tsc && vite build`). It looks like the esm files were built but not included in `"files"` in the `package.json`, and esnext was not built at all.  The individual instrumentations were fixed up with #1776 , but the same is needed for the metapackage.

I've opened #1848 to fix this.
