### ISSUE TITLE
 JS specific pentelemetry/instrumentation

### ISSUE THREAD

**Issue by SinghS99** [open-telemetry/opentelemetry-js-contrib#1835]
node --require @opentelemetry/auto-instrumentations-node/register index.js
Unable to initialize instrumentation for lambda. Cannot identify lambda handler or task root. { taskRoot: undefined, handlerDef: undefined }
@opentelemetry/instrumentation-grpc Module @grpc/grpc-js has been loaded before @opentelemetry/instrumentation-grpc so it might not work, please initialize it before requiring @grpc/grpc-js
OTEL_TRACES_EXPORTER is empty. Using default otlp exporter.
OpenTelemetry automatic instrumentation started successfully

**Comment by pichlermarc** [comment]
> node --require @opentelemetry/auto-instrumentations-node/register index.js Unable to initialize instrumentation for lambda. Cannot identify lambda handler or task root. { taskRoot: undefined, handlerDef: undefined } 

This is #1774

> @opentelemetry/instrumentation-grpc Module @grpc/grpc-js has been loaded before @opentelemetry/instrumentation-grpc so it might not work, please initialize it before requiring @grpc/grpc-js 

This is https://github.com/open-telemetry/opentelemetry-js/issues/4151, I'm working on this. PR to follow soon.

> OTEL_TRACES_EXPORTER is empty. Using default otlp exporter.

You can set the exporter specifically using the `OTEL_TRACES_EXPORTER` environment variable, then this log will go away. (I highly recommend this, it's better to be explicit with this config, it fits the definition of its log level - code may continue to work, but it's unconfigured and may cause problems for your specific setup).

> OpenTelemetry automatic instrumentation started successfully

This is an info log. I think this is fine.
If the logging is too verbose, you can also set the `OTEL_LOG_LEVEL` env var to `WARN` or `ERROR`. 

Since we already have issues for this I'm closing this as a duplicate, feel free to comment if you disagree - happy to re-open the issue then.
