### ISSUE TITLE
instrumentation-pino - the same span_id is logged for all the logs of the trace_id

### ISSUE THREAD

**Issue by alaajassar0** [open-telemetry/opentelemetry-js-contrib#1869]
### What version of OpenTelemetry are you using?
```
"@opentelemetry/exporter-trace-otlp-http": "0.39.1",
"@opentelemetry/instrumentation-aws-sdk": "0.34.2",
"@opentelemetry/instrumentation-http": "0.39.1",
"@opentelemetry/instrumentation-mysql": "0.33.2",
"@opentelemetry/instrumentation-pino": "0.34.4",
"@opentelemetry/resources": "1.13.0",
"@opentelemetry/sdk-node": "0.39.1",
"@opentelemetry/sdk-trace-node": "1.13.0",
"@opentelemetry/semantic-conventions": "1.13.0",
"opentelemetry-instrumentation-express": "0.35.0",
"opentelemetry-instrumentation-kafkajs": "0.35.0"
```

Used Pino version:
v8.16.1

### What version of Node are you using?
v16.20.2

### What did you do?
Use instrumentation-pino to log trace_id & span_id of the traces of multiple instrumentations: MySQL, http, Kafka, etc..

### What did you expect to see?
multiple span_id are logged for each trace_id.

### What did you see instead?
While trace_id is logged as expected, the same span_id is logged for all of the logs of the trace_id, instead of multiple span_ids:
```
{"level":"info","trace_id":"e7ef1af978c40040e9a26eed32034d47","span_id":"241296f2bf27a308","trace_flags":"00","message":"App was updated in DB"}
{"level":"info","trace_id":"e7ef1af978c40040e9a26eed32034d47","span_id":"241296f2bf27a308","trace_flags":"00","message":"finished processing campaign"}
{"level":"info","trace_id":"e7ef1af978c40040e9a26eed32034d47","span_id":"241296f2bf27a308","trace_flags":"00","message":"processing campaign done"}
{"level":"info","trace_id":"e7ef1af978c40040e9a26eed32034d47","span_id":"241296f2bf27a308","trace_flags":"00","message":"Sending a kafka message"}
```
(There are 39 log lines with the same trace_id & span_id.. The 4 lines above are just some of the logs)

### Additional context
- Jaeger shows multiple span_id for the same trace_id, so it's probably an issue with the logger.
- The issue reproduces for Node 18 as well.
- Both regular Pino loggers and child loggers have this behavior.

**Comment by MikeQDev** [comment]
Are the spans you're seeing coming from [auto-]instrumentation libraries (instrumentation-mysql, instrumentation-http, etc.)?

If so, what you're seeing is expected behavior, since when you're logging, the library spans have already ended, and your application has returned to the root/'main' span when you're logging messages that result in the same spanId

The code I experimented with was:                         

```js
tracer.startActiveSpan('manual-span', span => {

    pinoLog.info('hello from pino');

    tracer.startActiveSpan('manual-span2', span2 => {
        pinoLog.info('hello from pino2');
        span2.end();
    });

    span.end();

});
```
 
Log records yield same trace_id and different span_ids:

```json
{"level":30,"time":1703170159839,"pid":8124,"trace_id":"089161ab5cec2e58713f8e4aa4b3e112","span_id":"a56a6043780383ef","trace_flags":"01","msg":"hello from pino"}
{"level":30,"time":1703170159840,"pid":8124,"trace_id":"089161ab5cec2e58713f8e4aa4b3e112","span_id":"c0e8e82af5bc1523","trace_flags":"01","msg":"hello from pino2"}
```

The above was produced with dependencies:
- pino@8.17.1
- @opentelemetry/instrumentation-pino@0.33.3
- node v20.2.0

(Disclaimer: not super familiar with pino or the instrumentation; was simply experimenting with logging a bit earlier this week and stumbled across your issue)

**Comment by alaajassar0** [comment]
@MikeQDev 
Just confirmed that this is actually the case.
Thanks a lot for the detailed explanation!
