### ISSUE TITLE
pg tests fail on node 14

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#24]
See build log here https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-js-contrib/20/workflows/86b033c2-7114-4093-8dbb-3bd537d206e1/jobs/119

cc/ @markwolff

**Comment by markwolff** [comment]
Caused by https://github.com/brianc/node-postgres/issues/2180
Looks like we will need to bump pg to `7.x`...`8.x`. How are we planning to handle testing across major versions, if at all? In the past, I've spun up separate folders to run the tests, but it's duped code for each major version bump.

**Comment by dyladan** [comment]
I think for beta, it is sufficient to support latest only. @mayurkale22 wdyt

**Comment by andrewhsu** [comment]
I agree with @dyladan given the current state of this project at this point.

In the future, if supporting different major versions of the same package is desired, may want to consider having major version (or whatever is appropriate for the specific contrib package because sometimes some projects break compatibility between minor versions) to separate stuff out (but only if necessary), e.g.:
* `opentelemetry-plugin-pg-8`
* `opentelemetry-plugin-pg-7`

**Comment by dyladan** [comment]
@markwolff we talked about it at the SIG and we're just going to bump to 8 at this stage. You want to make a PR or should I?
