### ISSUE TITLE
undici instrumentation does not set `http.url` attribute

### ISSUE THREAD

**Issue by timfish** [open-telemetry/opentelemetry-js-contrib#2417]
I've noticed that the undici instrumentation sets the `url.full` attribute but does not set the `http.url` attribute which I would expect for HTTP client spans.

It only sets these attributes:
https://github.com/open-telemetry/opentelemetry-js-contrib/blob/9dc58afed8134f95908331bcff35c5d9ec46fe9a/plugins/node/instrumentation-undici/src/undici.ts#L178-L185

**Comment by timfish** [comment]
Ah, looking at [this discussion](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1951#discussion_r1513161091), this is intensional?

**Comment by pichlermarc** [comment]
Ah yes, that's intentional. We made it use the latest (stable) semconv, and `@opentelemetry/instrumentation-http` is still using the old one. @dyladan is currently working on updating `@opentelemetry/instrumentation-http`, and the spans attributes will then also eventually resemble what the `@opentelemetry/instrumentation-undici` package produces.

**Comment by pichlermarc** [comment]
Core PR updating `@opentelemetry/instrumentation-http` for future reference: https://github.com/open-telemetry/opentelemetry-js/pull/4940

**Comment by timfish** [comment]
Ok, closing this since it's not a bug!
