### ISSUE TITLE
Update koa plugin to specify route in span name

### ISSUE THREAD

**Issue by akshah123** [open-telemetry/opentelemetry-js-contrib#262]
**Is your feature request related to a problem? Please describe.**
Recently, plugin-http was updated to not have pathname in the span name: https://github.com/open-telemetry/opentelemetry-js/pull/1466

It was done with expectation that other plugins like express would add parameterized route in the span name.

Unfortunately, koa plugin doesn't do this so upgrading to the latest opentelemetry version causes traces to be less useful.

**Describe the solution you'd like**
It would be great if koa plugin can update span name similar to how express does it here: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/176

**Describe alternatives you've considered**
None.

**Comment by obecny** [comment]
@akshah123 
I’m trying to understand what do you mean by saying `It would be great if koa plugin can update span name similar to how express does it here`, because this is what I see in some knex / koa postgresql application

[Screenshots](https://imgur.com/a/skn57s6)

Can you please tell me what is wrong here ?

**Comment by akshah123** [comment]
@obecny I didn't realize that route gets added as a separate span as well.  Initially, `HTTP Get` span used to have path name as well.  I think it should be fine to just have it as is.
