### ISSUE TITLE
faas.id incorrectly used as span attribute

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-contrib#442]
faas.id is used as a span attribute here, but should be a resource attribute. I left it here to make this PR as small as possible while passing and changing no behavior. I will create a follow up bug to fix this.

_Originally posted by @dyladan in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/440#r618493944_

**Comment by dyladan** [comment]
@willarmiros mind if I assign this to you?

**Comment by willarmiros** [comment]
@dyladan Sure!

**Comment by willarmiros** [comment]
It turns out this is actually a known issue. The `faas.id` cannot be a resource attribute because resource attributes must be set at initialization time and are thereafter immutable. However a Lambda function's ARN (which is its `faas.id`) is only readable from the context of a function invocation. So it is impossible to assign it at initialization time and is made a span attribute as a workaround instead.

Here's the original spec issue pointing this out: https://github.com/open-telemetry/opentelemetry-specification/issues/1261

This would either be solved by:
1. Getting the Lambda team to expose the ARN at startup (we're trying!), or
2. https://github.com/open-telemetry/opentelemetry-specification/issues/1298, which would allow some resource attribs (like `faas.id` to be mutable)

**Comment by dyladan** [comment]
@willarmiros looks like there has been no spec movement on this since trace GA. Think now might be a good time to try to tackle this?

**Comment by willarmiros** [comment]
Unfortunately due to internal limitations Lambda is not able to expose its ARN at startup. So it seems we are blocked on https://github.com/open-telemetry/opentelemetry-specification/issues/1298 to get this fixed.

**Comment by Flarna** [comment]
Meanwhile spec allows to set `faas.id` as span attribute instead as resource attribute: _On some cloud providers, it may not be possible to determine the full ID at startup, so consider setting faas.id as a span attribute instead._

For AWS it would be possible to set it on resource by delaying resource detection until first invocation but on e.g. azure a single OS process (and therefore single global TracerProvider) may host several functions which have different ids therefore resource is not applicable at all.

see: https://github.com/open-telemetry/opentelemetry-specification/pull/2502

**Comment by dyladan** [comment]
interesting I missed that wording in the spec. thanks for clarifying. i'll close this then
