### ISSUE TITLE
ci: automation to cut release automatically when core one is done to keep versions in sync

### ISSUE THREAD

**Issue by vmarchaud** [open-telemetry/opentelemetry-js-contrib#457]
Based on https://github.com/open-telemetry/opentelemetry-js-contrib/issues/448. We need to answer different questions before implementing this:
- if a release is cut for contrib but not for core, do we sync it to core ? Generally does it works both way ?
- what if breaking changes happens ? we could make an automatic PR but this would still require human to fix it, since contrib have 3rd party code, how do we handle this ?

**Comment by obecny** [comment]
well it will de sync sooner or later, once we release 1.0 it might be in sync for a while, but later there is a chance it will desync anyway. I would not be worry about it, these are 2 repos anyway.

**Comment by dyladan** [comment]
If we don't sync them, we at least need a way to make it immediately obvious which versions are compatible without having to check some readme.

1 possible solution is to peer depend on API. If we peer depend on the compatible API version, it will complain at install time if the API version the user installed is incompatible. Since the instrumentations only use the API and don't interact directly with SDK, this should be fine.

**Comment by lizthegrey** [comment]
> If we don't sync them, we at least need a way to make it immediately obvious which versions are compatible without having to check some readme.
> 
> 1 possible solution is to peer depend on API. If we peer depend on the compatible API version, it will complain at install time if the API version the user installed is incompatible. Since the instrumentations only use the API and don't interact directly with SDK, this should be fine.
> 
> This is basically the same reason we decided to do this for core, and i've seen other "in the wild" plugins and instrumentations do it this way too.

+1 that peerDependencies are the right way to warn on this.

**Comment by vmarchaud** [comment]
I'll go ahead and close this, we implemented a while ago peerDependency on the api
