### ISSUE TITLE
aws-lambda: Add attributes to identify cold start and lambda runtime container

### ISSUE THREAD

**Issue by mooyoul** [open-telemetry/opentelemetry-js-contrib#703]
### Is your feature request related to a problem? Please describe

Currently, There are no attributes to indicate given lambda invocation was cold-started, or not.
(Semantic Attributes exposed this as `FAAS_COLDSTART` btw)

Also, Sometimes i need to know which "lambda container" handled given invocation.
For example, If there was problematic lambda runtime which has broken pipes (or sockets, etc.) and subsequent calls handled by problematic lambda runtime were failed, It's hard to investigate issues.

### Describe the solution you'd like to see

```
let containerId: string | null = null;
if (!containerId) {
  containerId = generateContainerId();
  setAttribute(FAAS_COLDSTART, true);
  setAttribute(FAAS_INSTANCE, containerId);
} else {
  setAttribute(FAAS_COLDSTART, false);
  setAttribute(FAAS_INSTANCE, containerId);
}
```

### Describe alternatives you've considered

As far as i know, There's no way to get container id. So we need to generate random value and use this as container id.
I'm not sure that log stream can be used as container id. If log stream can be used as container id, we don't need to generate container id.

### Additional context

I want to hear feedback. So ping component owners: @willarmiros @NathanielRN

**Comment by willarmiros** [comment]
There is no `faas.coldstart` attribute defined in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/faas.md), but I think it would be useful to many people. I think you could propose adding it to the spec first, and if accepted I would be in favor of recording it in the Lambda resource detector as you proposed.

For FAAS_INSTANCE, the spec already recommends using the log stream name, so that's what I'd recommend to use here as well.

**Comment by mattfysh** [comment]
Hey all, I'd be interested in this also for grouping traces by coldstart or not, and understanding % of invocations that were cold booted.

It also seems sensible to have this as an `index_attribute` in the awsxray exporter, does that make sense?

Cheers

**Comment by dyladan** [comment]
> And i have a question: Is there cleaner way to implement cold-start detection in detectors? Detectors usually called once on initialization step and never be called again.

The resource is not the correct place for a cold start detector because it is immutable. You only want the cold start on the first invocation, not every invocation.

> > For FAAS_INSTANCE, the spec already recommends using the log stream name, so that's what I'd recommend to use here as well.
> 
> Is single log stream dedicated to single container? Just curious.

Yes you get a new log stream for each instance. I could be wrong but I thought the container instance id was actually a part of the log stream name

**Comment by markandrus** [comment]
I previously computed this manually for inclusion in my traces. I'm trying to migrate to the @opentelemetry libraries, and having this would be great.
