### ISSUE TITLE
Graphql should add operation name and hash in span

### ISSUE THREAD

**Issue by Sytten** [open-telemetry/opentelemetry-js-contrib#705]
### Is your feature request related to a problem? Please describe

Currently the name of the operation and the hash are not provided in the attributes of the span. It just prints `query`, which is not even the operation name but the operation type. This makes it very difficult to find a given operation in all the traces.

### Describe the solution you'd like to see

By default the operation name should be provided as `operation.name` and the current `name` should be renamed to `type`.
Ideally the hash would also be provided. Getting a consistant is however difficult (each server implementation is different), so providing a hook for customization would be best with a sensible default.

### Describe alternatives you've considered

I considered using `envelop` instead and skip the plugin from opentelemetry, but this requires significant changes in the code.

### Additional context

<img width="610" alt="Screen Shot 2021-10-18 at 10 54 31 AM" src="https://user-images.githubusercontent.com/2366731/137755859-dd380450-d095-41c3-9e6e-1aa76427f1ed.png">

**Comment by jord1e** [comment]
> Semantic conventions are sets of attributes that standardize how attributes are set for various types of spans. The reason for this is so that if there are multiple instrumented libraries that are tracing the same types of calls (for example you are tracing graphql from 2 different libraries, or even languages), they get the same attributes. This makes it so they can be consistently processed by your tracing backend.
> 
> [open-telemetry/opentelemetry-specification@`main`/specification/trace/semantic_conventions/README.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/README.md?rgh-link-date=2021-10-27T14%3A40%3A02Z)
> 
> It looks like there isn't a semantic convention for graphql, but the database semconv and the rpc semconv might be partially applicable? I think this might be a good case to make an addition to the specification though.

Who would be the one to start the initiative to add GraphQL conventions to the spec?
As GraphQL is gaining popularity it should be a priority to have uniform telemetry data.

**Comment by jord1e** [comment]
@github-actions

**Comment by dchambers** [comment]
@Sytten, is there a particular reason why you think the field should be called `operation.name` rather than `graphql.operation.name`, otherwise #847 would seem (to me) to be the right approach? This would hopefully also avoid the need for a naming convention discussion, given that `@opentelemetry/instrumentation-graphql` already emits a `graphql.operation.name` field, and fixing it would just be an improvement to what it already does.

**Comment by Sytten** [comment]
I have no opinion on the name of the field per say, just that the current implementation is wrong. Changing it would be a breaking change in any case.

**Comment by jscherer92** [comment]
@dyladan can we get this closed?

GraphQL does have standard attributes on requests and responses and that is found in the specification found here:

Request: http://spec.graphql.org/October2021/#sec-Validating-Requests

Response: http://spec.graphql.org/October2021/#sec-Response-Format

So we can get this implemented in the instrumentation.

**Comment by Sytten** [comment]
Not stale

**Comment by dyladan** [comment]
>Who would be the one to start the initiative to add GraphQL conventions to the spec?
>As GraphQL is gaining popularity it should be a priority to have uniform telemetry data.

@jord1e Sorry for the late response. Anyone can submit a change to the opentelemetry spec. Following the steps in [`spec/CONTRIBUTING.md#Proposing a change`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change), the first step would be to [create an issue](https://github.com/open-telemetry/opentelemetry-specification/issues/new/choose). Once the issue is accepted by the spec maintainers, then a PR can be drafted. In this case there is already [an open issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1670) and [a PR](https://github.com/open-telemetry/opentelemetry-specification/pull/2456) which already has significant reviews.

@jscherer92 I'm sorry I wasn't clear I was referring to the OTel semantic convention specification. It looks like the process is already started with [an issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1670) and [a PR](https://github.com/open-telemetry/opentelemetry-specification/pull/2456) already opened. The PR also has significant reviews so I expect it will merge soon.

**Comment by Sytten** [comment]
Auto close bots are a bad practice
