### ISSUE TITLE
Instrument Redis transaction commands as child spans of a MULTI-EXEC span

### ISSUE THREAD

**Issue by nata7che** [open-telemetry/opentelemetry-js-contrib#807]
### Is your feature request related to a problem? Please describe

Redis enables executing commands as part of a [transaction](https://redis.io/topics/transactions):
```
> MULTI
OK
> SET foo bar
QUEUED
> INCR baz
QUEUED
> EXEC
1) (integer) 1
2) (integer) 1
```

This, currently, yields 4 spans:
1. operation: redis-multi
2. operation: redis-incr
3. operation: redis-set
4. operation: redis-exec 

It is very difficult to understand the results of each of the inner-transaction commands or the general status (success/failure) of the transaction with reference to the inner-transaction commands.
![image](https://user-images.githubusercontent.com/6080519/147666853-600d1c79-98f0-4e61-8158-15cfd062d902.png)

### Describe the solution you'd like to see

It could be beneficial if the inner-transaction commands could be child spans of the `redis-multi` span.
In addition, it could be amazing if somehow we can attach the results from `redis-exec` response and set it to the inner spans.

**Comment by dyladan** [comment]
I think this comes down to a question of your tracing philosophy. In my opinion, the current behavior is correct. The incr and set commands are still sent to the server, and the span still traces that operation even though they are queued and not run. Additionally, the send to the server for the incr and set commands was successful even if the exec command fails. WRT the parent-child relationship, I can see this argument both ways. My personal opinion is that these spans are all sibling spans, because one does not happen as a direct result of another one.
